### PR TITLE
UIPER-100

### PR DESCRIPTION
**Pull request by alb3rtino**

### CODE REVIEW

**Review by MikeTaylor — COMMENTED** [review]
Why has this change been made?

**Comment by alb3rtino** [comment]
https://issues.folio.org/browse/UIPER-100

Is it causing any problems?

**Comment by alb3rtino** [comment]
Linked in my previous comment.

**Comment by MikeTaylor** [comment]
Oh, yes, of course. My bad. And in fact I should have noticed the Jira issue number in the PR name.

Please add change-log entries.

**Pull request merged**
